# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
        - image: circleci/python:3.6.8-node
        - image: circleci/postgres:9.6-alpine
          environment: 
            POSTGRES_HOST: localhost
            POSTGRES_USER: ubuntu
            POSTGRES_DB: circle_test
        - image: circleci/redis

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run: sudo pip install --upgrade pip
      - run: # install and activate virtual environment with pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache: # special step to save dependency cache
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: sudo npm i -g less
      # Tests
      - run: . venv/bin/activate && flake8 inkshop --exclude=migrations --ignore=F401,F402,F403,F405,E722,E741,E402,E721,W503 --max-line-length=130
      - run: . venv/bin/activate && python3 manage.py test --settings=inkshop.envs.ci --parallel

  deploy-job:
    docker:
      - image: circleci/python:3.6.8-node
    working_directory: ~/repo  
    steps:
      - checkout
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Install less
          command: sudo npm i -g less
#       - run:
#            name: Push to Heroku
#            command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/YOUR_HEROKU_APP.git master
#       - run:
#            name: Migrate DB
#            command: heroku run "python manage.py migrate --settings=envs.live" --app YOUR_HEROKU_APP && echo "Migration Complete."
#       - run:
#            name: Compress static
#            command: heroku run "python manage.py compress --settings=envs.live_local && python manage.py compress --settings=envs.live" --app YOUR_HEROKU_APP
#       - run:
#            name: Collect static
#            command: heroku run "python manage.py collectstatic --settings=envs.live_local --noinput && python manage.py collectstatic --settings=envs.live --noinput" --app YOUR_HEROKU_APP
#       - run:
#            name: Purge Cloudflare Cache
#            command: 'sudo pip install requests; python bin/purge_cloudflare.py mail.YOURDOMAIN.com clubhouse.YOURDOMAIN.com'

workflows:
  version: 2

  deploy:
    jobs:
      - build-job:
          context: inkshop
      - deploy-job:
          context: inkshop
          requires:
            - build-job
          filters:
            branches:
              only: master

machine:
    python:
        version: 3.6.8
    services:
        - redis